<?php
require_once __DIR__ . '/includes/db_connection.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/master_data.php';
startSecureSession(); requireLogin();
$conn = getDBConnection(); ensurePODSchema($conn);
$query = trim($_GET['q'] ?? ''); $like = '%' . $query . '%';
$sql = 'SELECT id, consignment_note, booking_date, consignee_name, docket_tracking_status FROM consignments';
if ($query !== '') $sql .= ' WHERE consignment_note LIKE ? OR consignee_name LIKE ?';
$sql .= ' ORDER BY booking_date DESC LIMIT 300';
$stmt = $conn->prepare($sql); if ($query !== '') $stmt->bind_param('ss', $like, $like); $stmt->execute(); $rows = $stmt->get_result()->fetch_all(MYSQLI_ASSOC); $stmt->close();
$csrf = generateCSRFToken(); $statuses = ['In Transit','Connecting to Next Destination','Out for Delivery','Delivered','Hold','Return'];
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars(appBrandTitle('Docket Status')) ?></title><link rel="stylesheet" href="css/style.css"><style>.status-page{max-width:1180px;margin:12px auto}.status-row{display:grid;grid-template-columns:145px 1fr 105px 230px 90px;gap:8px;align-items:center;background:#fff;border:1px solid #b9d8d5;border-left:4px solid #0f766e;padding:8px;margin:5px 0;border-radius:6px;font-size:.72rem}.status-row.head{background:linear-gradient(90deg,#0f766e,#075985);color:#fff;border-left:0;font-weight:700}.status-row select{height:26px;border-color:#14b8a6}@media(max-width:800px){.status-row{grid-template-columns:1fr 1fr}.status-row.head{display:none}}</style></head><body><div class="app-shell"><aside class="app-sidebar"><?php renderAppBrand(); ?><nav class="sidebar-nav"><?php renderSidebarNav(); ?></nav><?php renderSidebarFooter(); ?></aside><div class="app-main"><?php renderAppHeader('Docket Status', '📍'); ?><main class="app-body"><div class="status-page"><form method="get" style="margin-bottom:10px"><input class="form-control" style="width:300px;display:inline-block" name="q" value="<?= htmlspecialchars($query) ?>" placeholder="Search docket or consignee"><button class="btn btn-primary btn-sm">Search</button></form><div class="status-row head"><span>Docket</span><span>Consignee</span><span>Booking</span><span>Status</span><span>Save</span></div><?php foreach ($rows as $row): ?><div class="status-row" data-id="<?= $row['id'] ?>"><b><?= htmlspecialchars($row['consignment_note']) ?></b><span><?= htmlspecialchars($row['consignee_name']) ?></span><span><?= htmlspecialchars($row['booking_date']) ?></span><select class="track-status"><?php foreach ($statuses as $status): ?><option <?= $row['docket_tracking_status'] === $status ? 'selected' : '' ?>><?= htmlspecialchars($status) ?></option><?php endforeach; ?></select><button class="btn btn-outline-primary btn-sm save-status">Save</button></div><?php endforeach; ?></div></main></div></div><script>const csrf=<?=json_encode($csrf)?>;document.querySelectorAll('.save-status').forEach(b=>b.onclick=async()=>{const r=b.closest('.status-row'),f=new FormData();f.append('csrf_token',csrf);f.append('consignment_id',r.dataset.id);f.append('docket_tracking_status',r.querySelector('.track-status').value);const d=await(await fetch('api/update_docket_status.php',{method:'POST',body:f})).json();alert(d.message)});</script></body></html>
