<?php
require_once __DIR__ . '/includes/db_connection.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/master_data.php';
startSecureSession(); requireLogin();
$conn = getDBConnection();
$view = ($_GET['view'] ?? 'pending') === 'uploaded' ? 'uploaded' : 'pending';
$query = trim($_GET['q'] ?? '');
$rows = getPODQueue($conn, $view, $query);
$csrf = generateCSRFToken();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars(appBrandTitle('POD Upload')) ?></title><link rel="stylesheet" href="css/style.css"><style>.pod-page{max-width:1450px;margin:12px auto;padding:0 12px}.pod-toolbar,.pod-row{display:grid;grid-template-columns:92px 1.1fr 100px 150px 85px 120px 235px;gap:8px;align-items:center}.pod-toolbar{margin:12px 0}.pod-row{background:#fff;border:1px solid #d8e0e8;border-radius:6px;padding:7px 9px;margin:5px 0;font-size:.72rem}.pod-row.head{background:#1a5276;color:#fff;font-weight:700}.pod-row small{color:#64748b}.pod-row input,.pod-row select{width:100%;height:25px}.pod-file{font-size:.62rem}.pod-action{display:flex;gap:4px}.pod-status{font-weight:700}.pod-status.delivered{color:#16803c}.pod-status.pending{color:#b7791f}@media(max-width:1000px){.pod-toolbar,.pod-row{grid-template-columns:1fr 1fr}.pod-row.head{display:none}}</style></head>
<body><div class="app-shell"><aside class="app-sidebar"><?php renderAppBrand(); ?><nav class="sidebar-nav"><?php renderSidebarNav(); ?></nav><?php renderSidebarFooter(); ?></aside><div class="app-main"><header class="app-header"><h1>📄 POD Upload Queue</h1><div class="header-actions"><a href="pod_upload.php?view=pending" class="btn btn-sm <?= $view === 'pending' ? 'btn-light' : 'btn-outline-light' ?>">Pending</a><a href="pod_upload.php?view=uploaded" class="btn btn-sm <?= $view === 'uploaded' ? 'btn-light' : 'btn-outline-light' ?>">Uploaded</a><?php $_br=currentUserBranchName();$_brSuffix='';if($_br&&$_br!=='—'){$_bc=currentUserBranchCode();$_brSuffix=' · '.htmlspecialchars(($_bc?$_bc.' — ':'').$_br);}?><span class="user-info"><?= htmlspecialchars($_SESSION['username']) ?> (<?= htmlspecialchars($_SESSION['role']) ?>)<?= $_brSuffix ?></span><a href="logout.php" class="btn btn-outline-light btn-sm">Logout</a></div></header><main class="app-body"><div class="pod-page">
<script>document.addEventListener('DOMContentLoaded',()=>document.querySelector('div[style*="position:fixed"]')?.remove());</script><form class="pod-toolbar" method="get"><input type="hidden" name="view" value="<?= $view ?>"><input class="form-control" style="grid-column:span 3" name="q" value="<?= htmlspecialchars($query) ?>" placeholder="Search docket no. or consignee"><button class="btn btn-primary btn-sm">Search</button><span style="grid-column:span 3"><?= count($rows) ?> dockets shown · files: PDF/JPG/PNG/WEBP, max 2 MB each</span></form>
<div class="pod-row head"><span>Priority</span><span>Docket / Consignee</span><span>Booking</span><span>Delivery</span><span>Files</span><span>Save status</span><span>Upload POD</span></div>
<?php foreach ($rows as $row): ?><div class="pod-row" data-id="<?= $row['id'] ?>"><select class="pod-priority"><option <?= $row['pod_priority']==='Normal'?'selected':'' ?>>Normal</option><option <?= $row['pod_priority']==='High'?'selected':'' ?>>High</option><option <?= $row['pod_priority']==='Urgent'?'selected':'' ?>>Urgent</option></select><span><b><?= htmlspecialchars($row['consignment_note']) ?></b><br><small><?= htmlspecialchars($row['consignee_name']) ?></small></span><span><?= htmlspecialchars($row['booking_date']) ?></span><span><input class="pod-date" type="date" value="<?= htmlspecialchars($row['delivery_date'] ?? '') ?>"><small class="pod-status <?= $row['delivery_date'] ? 'delivered' : 'pending' ?>"><?= $row['delivery_date'] ? 'Delivered' : 'Not delivered' ?></small></span><span><?= (int)$row['pod_count'] ?> file(s)<?php if ($row['pod_count']): ?> · <a href="pod_files.php?id=<?= $row['id'] ?>">View</a><?php endif; ?></span><button type="button" class="btn btn-outline-primary btn-sm pod-save">Save</button><span class="pod-action"><input class="pod-file" type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp"><button type="button" class="btn btn-primary btn-sm pod-upload">Upload</button></span></div><?php endforeach; ?>
<?php if (!$rows): ?><p style="text-align:center;padding:30px">No dockets in this list.</p><?php endif; ?></div></main></div></div>
<div style="position:fixed;right:14px;bottom:14px;display:flex;gap:6px"><a href="index.php" class="btn btn-outline-primary btn-sm">Docket Entry</a><a href="docket_status.php" class="btn btn-primary btn-sm">Docket Status</a></div><script>const csrf=<?= json_encode($csrf) ?>; async function post(url,data){const r=await fetch(url,{method:'POST',body:data});return r.json()} document.querySelectorAll('.pod-save').forEach(b=>b.onclick=async()=>{const r=b.closest('.pod-row'),f=new FormData();f.append('csrf_token',csrf);f.append('consignment_id',r.dataset.id);f.append('pod_priority',r.querySelector('.pod-priority').value);f.append('delivery_date',r.querySelector('.pod-date').value);const d=await post('api/update_pod_status.php',f);alert(d.message);if(d.success)location.reload()});document.querySelectorAll('.pod-upload').forEach(b=>b.onclick=async()=>{const r=b.closest('.pod-row'),files=r.querySelector('.pod-file').files;if(!files.length)return alert('Select POD files first');const f=new FormData();f.append('csrf_token',csrf);f.append('consignment_id',r.dataset.id);for(const file of files)f.append('pod_files[]',file);const d=await post('api/upload_pod.php',f);alert(d.message);if(d.success)location.reload()});</script></body></html>
