-- E-Way Bill Dockets table (auto-created by ensureEwaybillSchema on first use)
-- Run manually only if needed; the app creates this table automatically.

CREATE TABLE IF NOT EXISTS ewaybill_dockets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ewb_no VARCHAR(12) NOT NULL,
    eway_bill_date VARCHAR(50) DEFAULT NULL,
    valid_from VARCHAR(50) DEFAULT NULL,
    valid_upto VARCHAR(50) DEFAULT NULL,
    consignor_name VARCHAR(200) DEFAULT NULL,
    consignor_gstin VARCHAR(15) DEFAULT NULL,
    consignor_address TEXT DEFAULT NULL,
    consignor_place VARCHAR(100) DEFAULT NULL,
    consignor_pincode VARCHAR(10) DEFAULT NULL,
    consignee_name VARCHAR(200) DEFAULT NULL,
    consignee_gstin VARCHAR(15) DEFAULT NULL,
    consignee_address TEXT DEFAULT NULL,
    consignee_place VARCHAR(100) DEFAULT NULL,
    consignee_pincode VARCHAR(10) DEFAULT NULL,
    doc_no VARCHAR(50) DEFAULT NULL,
    doc_date VARCHAR(20) DEFAULT NULL,
    doc_type VARCHAR(20) DEFAULT NULL,
    invoice_value DECIMAL(14,2) DEFAULT NULL,
    goods_details TEXT DEFAULT NULL,
    hsn_details TEXT DEFAULT NULL,
    actual_distance INT DEFAULT NULL,
    vehicle_no VARCHAR(30) DEFAULT NULL,
    transporter_id VARCHAR(20) DEFAULT NULL,
    transporter_name VARCHAR(200) DEFAULT NULL,
    part_a_json TEXT DEFAULT NULL,
    part_b_json TEXT DEFAULT NULL,
    items_json TEXT DEFAULT NULL,
    current_status VARCHAR(30) DEFAULT NULL,
    raw_response LONGTEXT DEFAULT NULL,
    consignment_id INT DEFAULT NULL,
    remarks TEXT DEFAULT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('Draft','Submitted') NOT NULL DEFAULT 'Draft',
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ewb_no (ewb_no),
    INDEX idx_ewb_status (current_status),
    INDEX idx_ewb_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
